name: csp
description: A library to solve constraint satisfaction problems
version: 0.0.1
repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
